using Microsoft.Maui.Storage;

namespace MAUIAppTest
{
    public partial class App : Application
    {
        private readonly Services.DatabaseService _dbService;
        private readonly EmployeePage _employeePage;

        public App(EmployeePage employeePage, Services.DatabaseService dbService)
        {
            InitializeComponent();

            _dbService = dbService;
            _employeePage = employeePage;

            //MainPage = _employeePage;
            //var NavPage = new NavigationPage(_employeePage);
            var NavPage = new NavigationPage(new DemoFlyOutPage(dbService));
            NavPage.BarBackground = Colors.Green;
            NavPage.BarTextColor = Colors.Red;

            MainPage = NavPage;
            //MainPage = new DemoTabedPage();
        }

        protected override void OnStart()
        {
            base.OnStart();

            // Warm the DB and refresh UI when the app starts
            if (_employeePage.BindingContext is ViewModels.EmployeeViewModel vm)
            {
                // Invoke the generated LoadEmployees command (generated by [RelayCommand] as LoadEmployeesCommand)
                vm.LoadEmployeesCommand.Execute(null);
            }

            Preferences.Default.Set("App_Last_Started", DateTime.UtcNow.ToString("O"));
        }

        protected override void OnSleep()
        {
            base.OnSleep();

            // Persist a simple timestamp when app goes to background
            Preferences.Default.Set("App_Last_Slept", DateTime.UtcNow.ToString("O"));

            // Optionally clear transient UI state to avoid stale input when resumed
            if (_employeePage.BindingContext is ViewModels.EmployeeViewModel vm)
            {
                vm.ClearFormCommand.Execute(null);
            }
        }

        protected override void OnResume()
        {
            base.OnResume();

            // Refresh data when the app resumes
            if (_employeePage.BindingContext is ViewModels.EmployeeViewModel vm)
            {
                vm.LoadEmployeesCommand.Execute(null);
            }

            Preferences.Default.Set("App_Last_Resumed", DateTime.UtcNow.ToString("O"));
        }
    }
}