using Microsoft.Maui.Storage;

namespace MAUIAppTest
{
    public partial class App : Application
    {
        private readonly Services.DatabaseService _dbService;
        private readonly EmployeePage _employeePage;

        private readonly LoginPage _loginPage;
        private readonly Services.ErrorHandlingService _errorHandler;

        public App(EmployeePage employeePage, Services.DatabaseService dbService, LoginPage loginPage, Services.ErrorHandlingService errorHandler)
        {
            InitializeComponent();

            _dbService = dbService;
            _employeePage = employeePage;
            _loginPage = loginPage;
            _errorHandler = errorHandler;

            //MainPage = _employeePage;
            //var NavPage = new NavigationPage(_employeePage);
            //var NavPage = new NavigationPage(new DemoFlyOutPage(dbService));
            // We start with the LoginPage as the root. Successful login will replace MainPage.
            // Keep a default NavPage reference for cases where other code expects a NavigationPage.
            var NavPage = new NavigationPage(_loginPage);
            //var NavPage = new NavigationPage(new DemoPage(dbService));

            NavPage.BarBackground = Colors.Blue;
            NavPage.BarTextColor = Colors.White;

            MainPage = NavPage;
            //MainPage = new DemoTabedPage();

            // Fire-and-forget apply saved theme at construction (will not block startup)
            _ = ApplySavedThemeAsync();

            // Global exception handlers for non-UI and UI thread exceptions
            AppDomain.CurrentDomain.UnhandledException += async (s, e) =>
            {
                if (e.ExceptionObject is Exception ex)
                    await _errorHandler.LogExceptionAsync(ex, "AppDomain.CurrentDomain.UnhandledException");
            };

            TaskScheduler.UnobservedTaskException += async (s, e) =>
            {
                await _errorHandler.LogExceptionAsync(e.Exception, "TaskScheduler.UnobservedTaskException");
            };

            // Platform-specific UI thread unhandled exceptions
#if WINDOWS || ANDROID || IOS
            Application.Current!.Dispatcher.Dispatch(() => { });
#endif
        }

        protected override void OnStart()
        {
            base.OnStart();
            // ensure theme applied again on start
            // Warm the DB and refresh UI when the app starts
            if (_employeePage.BindingContext is ViewModels.EmployeeViewModel vm)
            {
                // Invoke the generated LoadEmployees command (generated by [RelayCommand] as LoadEmployeesCommand)
                vm.LoadEmployeesCommand.Execute(null);
            }

            Preferences.Default.Set("App_Last_Started", DateTime.UtcNow.ToString("O"));
            // ensure theme applied again on start
            _ = ApplySavedThemeAsync();

        }
        protected override void OnSleep()
        {
            base.OnSleep();
            // no-op here: preferences are persisted to sqlite as changes happen
            // Persist a simple timestamp when app goes to background
            Preferences.Default.Set("App_Last_Slept", DateTime.UtcNow.ToString("O"));

            // Optionally clear transient UI state to avoid stale input when resumed
            if (_employeePage.BindingContext is ViewModels.EmployeeViewModel vm)
            {
                vm.ClearFormCommand.Execute(null);
            }
        }

        protected override void OnResume()
        {
            base.OnResume();
            // re-apply saved theme and refresh data if desired
            _ = ApplySavedThemeAsync();

            // Refresh data when the app resumes
            if (_employeePage.BindingContext is ViewModels.EmployeeViewModel vm)
            {
                vm.LoadEmployeesCommand.Execute(null);
            }

            Preferences.Default.Set("App_Last_Resumed", DateTime.UtcNow.ToString("O"));
        }

        private async Task ApplySavedThemeAsync()
        {
            var theme = await _dbService.GetPreferenceAsync("App_Theme");
            if (string.IsNullOrWhiteSpace(theme)) return;

            // Ensure UI update on main thread
            Application.Current?.Dispatcher.Dispatch(() =>
            {
                if (Enum.TryParse<AppTheme>(theme, ignoreCase: true, out var parsed))
                    Application.Current.UserAppTheme = parsed;
                else
                    Application.Current.UserAppTheme = AppTheme.Unspecified;
            });
        }
    }
}