namespace MAUIAppTest;

public partial class EmployeePage : ContentPage
{
    // The InitializeComponent method is generated by the XAML compiler.
    // This error usually means the corresponding EmployeePage.xaml file is missing,
    // not set to "MauiXaml" build action, or the .g.cs file is not being generated.
    // Ensure EmployeePage.xaml exists and is included in the project with the correct build action.

    public EmployeePage(ViewModels.EmployeeViewModel viewModel)
    {
        InitializeComponent();
        BindingContext = viewModel;
    }
}